config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :roles
  root :to => "roles#index"
  # get "active_role_users" => "user#active_role_users"
  get "add_meta_data" => "users#add_meta_data" 
  post "create_meta_data" => "users#create_meta_data"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
	validates :name, uniqueness: true
	scope :active, -> { where(is_default: true) }



	def self.active_roles
		result = {}
		self.active.each{|r| result[r.id] = r.name }
		return result
	end
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :role
	has_many :user_infos
	has_one_attached :photos
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  # after_action :set_variables, only:[:create]
  # GET /roles
  # GET /roles.json
  def index
    @role = Role.new
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    respond_to do |format|
      if @role.save
        @errors = @role.errors
        format.js
      else
        @errors = @role.errors.try(:full_messages)
        format.js
      end
    end
    @role = Role.new
    @roles = Role.all
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    @role = Role.new
    respond_to do |format|
      @roles = Role.all
      format.js
    end
  end

  private
    def set_role
      @role = Role.find(params[:id])
    end

    def role_params
      params.require(:role).permit(:name,:is_default)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy,:add_meta_data]

  # GET /users
  # GET /users.json
  def index
    @user = User.new
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        @errors = @user.errors
        format.js
      else
        @errors = @user.errors.try(:full_messages)
        format.js
      end
      @user = User.new
      @users = User.all
    end
  end

  def create_meta_data
    @user_info = UserInfo.new(data_type: params[:data_type],value: params[:value],user_id: params[:user_id])
    respond_to do |format|
      if @user_info.save
        @errors = @user_info.errors
        format.js
      else
        @errors = @user_info.errors.try(:full_messages)
        format.js
      end
      @user = User.find(params[:id])
    end
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    @user = User.new
    respond_to do |format|
      @users = User.all
      format.js
    end
  end


  def add_meta_data 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role_id, :last_name, :first_name, :email,:photos)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <div id="page-content-wrapper">
      <%= render './theme/header' %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/roles/_form.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Active</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each_with_index do |role,index| %>
      <tr>
        <td scope="row"><%= index+1%></td>
        <td><%= best_in_place role, :name, :as => :input %></td>
        <td>
          <%= best_in_place role, :is_default, as: :checkbox, collection: {false: "in active", true: "active"} %>
        </td>
        <td><%= link_to 'Destroy', role, method: :delete,remote:true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $(".best_in_place").best_in_place();
  });
</script>

app/views/roles/create.js.erb
<%if @errors.present? %>
	alert('error on creating role')
<% end %>
$(".role-list").html("<%= escape_javascript(render 'form') %>");

app/views/roles/destroy.js.erb
alert('Deleted Succefully')
$(".role-list").html("<%= escape_javascript(render 'form') %>");

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<%= form_with(model: @role, remote: true) do |form| %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Role Name</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">role</div>
        </div>
        <%= form.text_field :name, class: "form-control",id: "inlineFormInputGroup" %>
        <!-- <input type="text" class="form-control" id="" placeholder="Username"> -->
      </div>
    </div>
    <div class="col-auto">
      <div class="form-check mb-2">
        <%= form.check_box :is_default, checked: @role.is_default %>
        <!-- <input class="form-check-input" type="checkbox" id="autoSizingCheck"> -->
        <label class="form-check-label" for="autoSizingCheck">
          Is Active
        </label>
      </div>
    </div>
    <div class="col-auto">
      <%= form.submit class:"btn btn-primary mb-2"%> 
    </div>
  </div>
<%end%>

<div class="role-list">
  <%=render 'form' %>
</div>

app/views/theme/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
<!-- <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span> 
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="<%= users_path%>">Users <span class="sr-only"></span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="<%= roles_path%>">Roles <span class="sr-only">(current)</span></a>
      </li>
    </ul> 
  </div>
</nav>

app/views/users/_form.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope='col'>Role</th>
      <th scope="col">image</th>
      <th scope='col'>Meta Data</th>
      <th scope='col'>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user,index| %>
      <tr>
        <td scope="row"><%= index+1%></td>
        <td><%= best_in_place user, :first_name, :as => :input %></td>
        <td><%= best_in_place user, :last_name, :as => :input %></td>
        <td><%= best_in_place user, :email, :as => :input %></td>
        <td> 
          <%= best_in_place user, :role_id, :as => :select, :collection => Role.active_roles %>
        </td>
        <td><%= image_tag url_for(user.photos) if @user.photos.attached? %></td>
        <td><%= link_to "Meta Data", add_meta_data_path(:id => user.id) %></td>
        <td>
          <%= link_to 'Destroy', user, method: :delete,remote:true, data: { confirm: 'Are you sure?' } %>      
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $(".best_in_place").best_in_place();
  });
</script>

app/views/users/_form_user_info.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Data Type</th>
      <th scope="col">Value</th>
      <th scope="col">User</th>
      <th scope='col'>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @user.user_infos.each_with_index do |user,index| %>
      <tr>
        <td scope="row"><%= index+1%></td>
        <td>
          <%= user.data_type %>
        </td>
        <td><%= user.value %>
        </td>
        <td><%= user.user.name %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%#= link_to 'Destroy', delete_user_info(user.id),remote:true, data: { confirm: 'Are you sure?' } %>      
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function() {
    $(".best_in_place").best_in_place();
  });
</script>

app/views/users/add_meta_data.html.erb
<%= form_with(url:create_meta_data_path, model: @user_info, remote: true) do |form| %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Meta Data</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">Data Type</div>
        </div>
        <%= form.text_field :data_type, class: "form-control",id: "inlineFormInputGroup" %>
        <!-- <input type="text" class="form-control" id="" placeholder="Username"> -->
      </div>
    </div>
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Value</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">Value</div>
        </div>
        <%= form.text_field :value, class: "form-control",id: "inlineFormInputGroup" %>
        <!-- <input type="text" class="form-control" id="" placeholder="Username"> -->
      </div>
      <%= form.hidden_field :user_id, :value => @user.id %>
    </div>
    <div class="col-auto">
      <%= form.submit class:"btn btn-primary mb-2"%> 
    </div>
  </div>
<%end%>

<div class="user-info-list">
  <%=render 'form_user_info' %>
</div>

app/views/users/create.js.erb
<%if @errors.present? %>
	alert('error on creating role')
<% end %>
$(".user-list").html("<%= escape_javascript(render 'form') %>");

app/views/users/create_meta_data.js.erb
<%if @errors.present? %>
	alert('error on creating role')
<% end %>
$(".user-info-list").html("<%= escape_javascript(render 'form_user_info') %>");

app/views/users/destroy.js.erb
alert('Deleted Succefully')
$(".user-list").html("<%= escape_javascript(render 'form') %>");

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= form_with(model: @user, remote: true, :html => { :multipart => true }) do |form| %>
  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">First Name</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">First Name</div>
        </div>
        <%= form.text_field :first_name, class: "form-control",id: "inlineFormInputGroup" %>
      </div>
    </div>
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Last Name</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">Last Name</div>
        </div>
        <%= form.text_field :last_name, class: "form-control",id: "inlineFormInputGroup" %>
      </div>
    </div>
    <div class="col-auto">
      <label class="sr-only" for="inlineFormInputGroup">Email</label>
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">role</div>
        </div>
        <%= form.text_field :email, class: "form-control",id: "inlineFormInputGroup" %>
      </div>
    </div>
    <div class="col-auto">
      <div class="form-check mb-2">
        <label class="form-check-label" for="autoSizingCheck">
          Role
        </label>
        <%= form.select(:role_id, Role.active.collect {|u| [u.name, u.id]}, :prompt => 'Select') %>
        <%#form.select(:, "role_id", Role.all.collect {|p| [ p.name, p.id ] }, { include_blank: true })%>
      </div>
    </div>
    <%= form.file_field :photos %>
    <div class="col-auto">
      <%= form.submit class:"btn btn-primary mb-2"%> 
    </div>
  </div>
<%end%>

<div class="user-list">
  <%=render 'form' %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>